"""
phoenixd provisioning (build spec §6) — the "nothing to configure" promise behind the wizard's
phoenixd payout tier.

It downloads the phoenixd release for this platform, first-runs it to generate `~/.phoenix`
(wallet seed + auto http-password), reads the password into the gitignored `.env.host`, and
installs a durable `phoenixd.service` plus a `sail-host` drop-in so the host node depends on it.

The 12-word seed is generated by phoenixd and lives only in `~/.phoenix/seed.dat`. We surface it
once to the LOCAL wizard for the operator to back up (matching the seed-backup screen) and never
store or transmit it anywhere else — no relay, no SAIL file, no log.

Kept separate from the `PhoenixdLightning` backend so the backend can be tested against a
hand-run phoenixd first. This module is platform/ops glue; import it lazily.
"""
from __future__ import annotations

import io
import os
import pathlib
import platform
import re
import socket
import stat
import subprocess
import tempfile
import time
import zipfile
from urllib.parse import urlparse

import httpx

DEFAULT_VERSION = "0.6.1"  # fallback if the GitHub API is unreachable; latest_version() overrides
RELEASES_API = "https://api.github.com/repos/ACINQ/phoenixd/releases/latest"
RELEASE_DL = "https://github.com/ACINQ/phoenixd/releases/download"

PHOENIX_DIR = pathlib.Path.home() / ".phoenix"
SEED_FILE = PHOENIX_DIR / "seed.dat"
CONF_FILE = PHOENIX_DIR / "phoenix.conf"


def install_dir() -> pathlib.Path:
    return pathlib.Path(
        os.getenv("PHOENIXD_INSTALL_DIR", str(pathlib.Path.home() / ".local/share/sail/phoenixd"))
    )


# --- platform / release resolution ------------------------------------------
def _platform_tag() -> str:
    sysname, machine = platform.system().lower(), platform.machine().lower()
    if sysname == "linux":
        return "linux-x64"
    if sysname == "darwin":
        return "macos-arm64" if machine in ("arm64", "aarch64") else "macos-x64"
    raise RuntimeError(f"unsupported platform for phoenixd: {sysname}/{machine}")


def latest_version() -> str:
    try:
        r = httpx.get(RELEASES_API, timeout=10.0, headers={"Accept": "application/vnd.github+json"})
        r.raise_for_status()
        return r.json()["tag_name"].lstrip("v")
    except (httpx.HTTPError, KeyError, ValueError):
        return DEFAULT_VERSION


def download_phoenixd(version: str | None = None, dest: pathlib.Path | None = None) -> pathlib.Path:
    """Download + unzip the phoenixd release for this platform; return the `phoenixd` binary path.
    Idempotent: if the binary already exists for `version`, reuse it."""
    version = version or latest_version()
    dest = dest or install_dir()
    tag = _platform_tag()
    binary = dest / f"phoenixd-{version}-{tag}" / "phoenixd"
    if binary.exists():
        return binary

    url = f"{RELEASE_DL}/v{version}/phoenixd-{version}-{tag}.zip"
    dest.mkdir(parents=True, exist_ok=True)
    with httpx.Client(follow_redirects=True, timeout=120.0) as c:
        r = c.get(url)
        r.raise_for_status()
        with zipfile.ZipFile(io.BytesIO(r.content)) as z:
            z.extractall(dest)
    if not binary.exists():
        raise RuntimeError(f"phoenixd binary not found after unzip: {binary}")
    binary.chmod(binary.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return binary


# --- reading what first-run produced (pure; unit-tested with fixtures) ------
def read_http_password(conf_path: pathlib.Path = CONF_FILE) -> str:
    """Parse `http-password=...` out of phoenix.conf (the auto-generated API password, secret)."""
    if not conf_path.exists():
        raise FileNotFoundError(f"phoenix.conf not found at {conf_path} — has phoenixd run yet?")
    for line in conf_path.read_text().splitlines():
        m = re.match(r"\s*http-password\s*=\s*(.+?)\s*$", line)
        if m:
            return m.group(1).strip().strip('"').strip("'")
    raise RuntimeError("http-password not present in phoenix.conf")


def resolve_api_password() -> str:
    """The phoenixd API password, with ~/.phoenix/phoenix.conf as the SINGLE SOURCE OF TRUTH.

    phoenixd regenerates the http-password per wallet, so a copy stored elsewhere (e.g. a stale
    PHOENIXD_API_PASSWORD in .env.host) drifts on every wallet change — import, restore, re-provision
    — and the daemon then authenticates with the wrong password (HTTP 401). Reading phoenix.conf each
    time means whatever wallet is active, we use that wallet's actual password. The
    PHOENIXD_API_PASSWORD env var is honored ONLY as a fallback when there's no local phoenix.conf
    (e.g. a remote phoenixd). Never logged."""
    try:
        return read_http_password(CONF_FILE)  # local phoenix.conf — the active wallet's real password
    except (FileNotFoundError, RuntimeError):
        pw = os.getenv("PHOENIXD_API_PASSWORD", "").strip()
        if pw:
            return pw  # explicit override for a non-default (e.g. remote) phoenixd
        raise RuntimeError(
            "no phoenixd API password: no local ~/.phoenix/phoenix.conf and PHOENIXD_API_PASSWORD unset")


def read_seed_words(seed_file: pathlib.Path = SEED_FILE) -> list[str]:
    """Read the BIP39 mnemonic phoenixd wrote to seed.dat. Returns the word list (12 or 24).
    Surfaced to the local wizard only — caller must not persist or transmit it."""
    if not seed_file.exists():
        raise FileNotFoundError(f"seed.dat not found at {seed_file} — has phoenixd run yet?")
    words = re.findall(r"[a-z]+", seed_file.read_text().lower())
    if len(words) not in (12, 24):
        raise RuntimeError(f"unexpected seed word count ({len(words)}) in {seed_file}")
    return words


def is_provisioned() -> bool:
    """True once phoenixd has generated its wallet (conf + seed present)."""
    return CONF_FILE.exists() and SEED_FILE.exists()


def secure_seed_files() -> dict:
    """Tighten permissions on phoenixd's secret files. seed.dat is the PLAINTEXT recovery phrase
    (phoenixd's design) and phoenix.conf holds the API password — phoenixd writes both world-readable
    (0644) by default, so any local user could read them. chmod them 0600 and the ~/.phoenix dir
    0700 as the file-perms backstop. Idempotent; safe to call on every startup. Returns what changed."""
    changed = {}
    targets = {PHOENIX_DIR: 0o700, SEED_FILE: 0o600, CONF_FILE: 0o600}
    for path, mode in targets.items():
        try:
            if path.exists() and (path.stat().st_mode & 0o777) != mode:
                path.chmod(mode)
                changed[str(path)] = oct(mode)
        except OSError:
            pass
    return changed


# --- first run --------------------------------------------------------------
def _api_port() -> tuple[str, int]:
    u = urlparse(os.getenv("PHOENIXD_API_URL", "http://127.0.0.1:9740"))
    return (u.hostname or "127.0.0.1", u.port or 9740)


def _port_in_use(host: str, port: int) -> bool:
    """True if something is already listening on host:port (so we don't launch a second phoenixd
    that would just fail to bind the API port and exit)."""
    try:
        with socket.create_connection((host, port), timeout=1):
            return True
    except OSError:
        return False


def first_run(binary: pathlib.Path, timeout: float = 90.0) -> None:
    """Boot phoenixd once so it generates ~/.phoenix (seed + http-password), wait for those files,
    then stop this bootstrap process — the durable phoenixd.service takes over afterwards. No-op if
    already provisioned.

    On failure, surface the REAL reason: a fresh-user provisioning that "silently" produced no
    ~/.phoenix was actually phoenixd exiting early (e.g. its API port already taken, or a runtime
    error) with its output discarded. We pre-flight the port and capture phoenixd's output so the
    wizard shows the cause instead of a bare exit code. The output is phoenixd's own startup log
    (node id / errors) — the seed is written only to ~/.phoenix/seed.dat, never to stdout."""
    if is_provisioned():
        return
    host, port = _api_port()
    if _port_in_use(host, port):
        raise RuntimeError(
            f"phoenixd API port {host}:{port} is already in use — another phoenixd (or a process "
            f"on that port) is running. Stop it before provisioning, or set PHOENIXD_API_URL.")

    log = tempfile.NamedTemporaryFile(mode="w+", prefix="phoenixd-firstrun-", suffix=".log",
                                      delete=False)
    proc = subprocess.Popen(
        [str(binary), "--agree-to-terms-of-service"],
        stdout=log, stderr=subprocess.STDOUT,
    )

    def _tail() -> str:
        try:
            log.flush()
            text = pathlib.Path(log.name).read_text(errors="replace").strip()
        except OSError:
            return ""
        return text[-500:].strip()

    try:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if is_provisioned():
                return
            if proc.poll() is not None:
                why = _tail()
                raise RuntimeError(
                    f"phoenixd exited early (code {proc.returncode}) before generating a wallet"
                    + (f": {why}" if why else " (no output captured)"))
            time.sleep(0.5)
        why = _tail()
        raise TimeoutError(
            f"phoenixd did not generate ~/.phoenix within {timeout}s"
            + (f"; last output: {why}" if why else ""))
    finally:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        log.close()
        try:
            os.unlink(log.name)
        except OSError:
            pass


# --- systemd units (pure text; unit-tested) ---------------------------------
def phoenixd_service_unit(binary: pathlib.Path, user: str | None = None) -> str:
    from host.service_setup import current_user  # process owner, not $USER (sudo/su safe)
    user = user or current_user()
    return (
        "[Unit]\n"
        "Description=phoenixd (SAIL host Lightning node)\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "StartLimitIntervalSec=0\n\n"
        "[Service]\n"
        "Type=simple\n"
        f"User={user}\n"
        f"ExecStart={binary} --agree-to-terms-of-service\n"
        "Restart=always\n"
        "RestartSec=5\n\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def sail_host_dropin() -> str:
    """Drop-in so sail-host starts after, and is wanted-by, phoenixd when this tier is active."""
    return "[Unit]\nWants=phoenixd.service\nAfter=phoenixd.service\n"


def write_units(binary: pathlib.Path, deploy_dir: pathlib.Path | None = None) -> dict:
    """Write the unit + drop-in into the (gitignored) deploy/ dir and return the install commands.
    Installation needs root, so we surface the exact commands rather than assume sudo here."""
    deploy_dir = deploy_dir or pathlib.Path(__file__).resolve().parent.parent / "deploy"
    deploy_dir.mkdir(parents=True, exist_ok=True)
    unit = deploy_dir / "phoenixd.service"
    dropin = deploy_dir / "sail-host.service.d-phoenixd.conf"
    unit.write_text(phoenixd_service_unit(binary))
    dropin.write_text(sail_host_dropin())
    return {
        "unit": str(unit),
        "dropin": str(dropin),
        "install_commands": [
            f"sudo cp {unit} /etc/systemd/system/phoenixd.service",
            "sudo mkdir -p /etc/systemd/system/sail-host.service.d",
            f"sudo cp {dropin} /etc/systemd/system/sail-host.service.d/phoenixd.conf",
            "sudo systemctl daemon-reload",
            "sudo systemctl enable --now phoenixd",
        ],
    }


def try_install_units(binary: pathlib.Path, deploy_dir: pathlib.Path | None = None) -> dict:
    """Write the units, then attempt a passwordless install; fall back to surfacing the commands
    (same policy as the sail-host restart). Returns a JSON-able dict."""
    info = write_units(binary, deploy_dir)
    steps = [c.split()[1:] for c in info["install_commands"]]  # drop the leading 'sudo'
    try:
        for argv in steps:
            proc = subprocess.run(["sudo", "-n", *argv], capture_output=True, text=True, timeout=30)
            if proc.returncode != 0:
                info.update(installed=False, install_required=True,
                            error=(proc.stderr or proc.stdout).strip()[:200])
                return info
        info["installed"] = True
        return info
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        info.update(installed=False, install_required=True, error=str(e))
        return info


# --- import an existing wallet ----------------------------------------------
def wallet_funded_status() -> tuple[bool | None, str]:
    """Best-effort: is the EXISTING ~/.phoenix wallet funded? Queries the running phoenixd with the
    password from phoenix.conf. Returns (funded, detail): funded=True if it holds a balance/fee
    credit or any channel, False if verifiably empty, None if phoenixd is unreachable (can't tell).
    Used so a never-funded auto-generated wallet doesn't block a deliberate import, while a REAL
    funded wallet still does."""
    import httpx
    if not is_provisioned():
        return (False, "no wallet present")
    try:
        pw = read_http_password()
    except Exception:  # noqa: BLE001
        return (None, "wallet present but phoenix.conf unreadable")
    base = os.getenv("PHOENIXD_API_URL", "http://127.0.0.1:9740").rstrip("/")
    try:
        c = httpx.Client(base_url=base, auth=("", pw), timeout=8.0)
        bal = c.get("/getbalance")
        if bal.status_code != 200:
            return (None, "phoenixd not reachable")
        b = bal.json()
        info = c.get("/getinfo")
        chans = info.json().get("channels", []) if info.status_code == 200 else []
        bsat, fc = int(b.get("balanceSat") or 0), int(b.get("feeCreditSat") or 0)
        funded = bsat > 0 or fc > 0 or len(chans) > 0
        return (funded, f"balance {bsat} sat, fee credit {fc} sat, {len(chans)} channel(s)")
    except (httpx.HTTPError, ValueError):
        return (None, "phoenixd not reachable")


def _stop_phoenixd_service() -> None:
    """Best-effort stop of the durable phoenixd.service so it stops regenerating/holding ~/.phoenix
    before we replace it. Then wait briefly for the API port to free up."""
    from host import config_writer
    config_writer.service_command("stop", service="phoenixd")  # sudo -n; ignore result (best effort)
    host, port = _api_port()
    deadline = time.monotonic() + 8
    while time.monotonic() < deadline and _port_in_use(host, port):
        time.sleep(0.5)


def _archive_phoenix_dir() -> pathlib.Path:
    """Move ~/.phoenix aside (never delete) so a replace is always recoverable. Returns the path."""
    dest = PHOENIX_DIR.parent / f".phoenix.replaced-{int(time.time())}"
    os.rename(PHOENIX_DIR, dest)
    return dest


def import_seed(words: list[str], replace: bool = False, version: str | None = None) -> dict:
    """Restore an EXISTING wallet from the operator's recovery phrase instead of generating one.

    phoenixd's getOrGenerateSeed() reads ~/.phoenix/seed.dat if it exists (else generates), so we
    write the mnemonic there FIRST — in phoenixd's own format (words joined by single spaces, which
    its `[a-z]+` reader parses) — then run the normal provision flow, where phoenixd restores that
    wallet. Caller MUST have validated the mnemonic (BIP39) already; phoenixd also validates on start.

    If a wallet already exists (commonly an auto-generated one from a prior 'create new' attempt, or
    one the durable phoenixd.service regenerated), `replace` must be True: we stop phoenixd.service
    and MOVE ~/.phoenix aside (never delete — always recoverable) before restoring. The caller is
    responsible for refusing to replace a FUNDED wallet (see wallet_funded_status). Never logs the seed."""
    if is_provisioned():
        if not replace:
            raise RuntimeError(
                f"a phoenixd wallet already exists at {PHOENIX_DIR} — pass replace=True to move it "
                f"aside and restore the imported seed")
        _stop_phoenixd_service()
        host, port = _api_port()
        if _port_in_use(host, port):
            raise RuntimeError(
                f"couldn't stop the running phoenixd ({host}:{port} still in use) — stop "
                f"phoenixd.service and retry the import")
        archived = _archive_phoenix_dir()
        print(f"[host] archived existing ~/.phoenix to {archived} before import")
    PHOENIX_DIR.mkdir(parents=True, exist_ok=True)
    SEED_FILE.write_text(" ".join(words))  # phoenixd seed.dat format: space-separated words
    secure_seed_files()                    # 0600 before phoenixd (and anyone) can read it
    result = provision(version)            # first_run finds seed.dat -> restores, doesn't generate
    restored = read_seed_words()
    if [w.lower() for w in restored] != [w.lower() for w in words]:
        raise RuntimeError("phoenixd did not restore the provided seed — wallet mismatch after import")
    result["imported"] = True
    return result


# --- orchestrator -----------------------------------------------------------
def provision(version: str | None = None) -> dict:
    """Full phoenixd setup. Returns the seed words (for the LOCAL wizard to display once) plus the
    service-install status. Writes PAYMENTS=phoenixd + PHOENIXD_API_URL into .env.host — NOT the
    password: the daemon reads that live from phoenix.conf (resolve_api_password), so it can't drift
    when the wallet changes."""
    from host import config_writer  # local import to avoid a cycle

    binary = download_phoenixd(version)
    first_run(binary)
    # Strict success contract: never return a seed (the wizard would run its back-up + verify
    # ceremony on it) unless the wallet actually persisted on disk. Guards against showing the
    # operator a recovery phrase for a node that was never created.
    if not is_provisioned():
        raise RuntimeError(
            f"phoenixd provisioning incomplete — expected wallet files under {PHOENIX_DIR} "
            f"(phoenix.conf + seed.dat) but they are missing")
    secure_seed_files()  # phoenixd writes seed.dat/phoenix.conf 0644 — tighten before we go further
    read_http_password()  # sanity: confirm a password is present in phoenix.conf (raises if not)
    seed_words = read_seed_words()  # surfaced locally only; never written elsewhere

    config_writer.update_env_file({
        "PAYMENTS": "phoenixd",
        "PHOENIXD_API_URL": os.getenv("PHOENIXD_API_URL", "http://127.0.0.1:9740"),
    })
    install = try_install_units(binary)
    return {"provisioned": True, "seed_words": seed_words, "service": install}
