"""
phoenixd provisioning (build spec §6) — the "nothing to configure" promise behind the wizard's
phoenixd payout tier.

It downloads the phoenixd release for this platform, first-runs it to generate `~/.phoenix`
(wallet seed + auto http-password), reads the password into the gitignored `.env.host`, and
installs a durable `phoenixd.service` plus a `sail-host` drop-in so the host node depends on it.

The 12-word seed is generated by phoenixd and lives only in `~/.phoenix/seed.dat`. We surface it
once to the LOCAL wizard for the operator to back up (matching the seed-backup screen) and never
store or transmit it anywhere else — no relay, no SAIL file, no log.

Kept separate from the `PhoenixdLightning` backend so the backend can be tested against a
hand-run phoenixd first. This module is platform/ops glue; import it lazily.
"""
from __future__ import annotations

import io
import os
import pathlib
import platform
import re
import stat
import subprocess
import time
import zipfile

import httpx

DEFAULT_VERSION = "0.6.1"  # fallback if the GitHub API is unreachable; latest_version() overrides
RELEASES_API = "https://api.github.com/repos/ACINQ/phoenixd/releases/latest"
RELEASE_DL = "https://github.com/ACINQ/phoenixd/releases/download"

PHOENIX_DIR = pathlib.Path.home() / ".phoenix"
SEED_FILE = PHOENIX_DIR / "seed.dat"
CONF_FILE = PHOENIX_DIR / "phoenix.conf"


def install_dir() -> pathlib.Path:
    return pathlib.Path(
        os.getenv("PHOENIXD_INSTALL_DIR", str(pathlib.Path.home() / ".local/share/sail/phoenixd"))
    )


# --- platform / release resolution ------------------------------------------
def _platform_tag() -> str:
    sysname, machine = platform.system().lower(), platform.machine().lower()
    if sysname == "linux":
        return "linux-x64"
    if sysname == "darwin":
        return "macos-arm64" if machine in ("arm64", "aarch64") else "macos-x64"
    raise RuntimeError(f"unsupported platform for phoenixd: {sysname}/{machine}")


def latest_version() -> str:
    try:
        r = httpx.get(RELEASES_API, timeout=10.0, headers={"Accept": "application/vnd.github+json"})
        r.raise_for_status()
        return r.json()["tag_name"].lstrip("v")
    except (httpx.HTTPError, KeyError, ValueError):
        return DEFAULT_VERSION


def download_phoenixd(version: str | None = None, dest: pathlib.Path | None = None) -> pathlib.Path:
    """Download + unzip the phoenixd release for this platform; return the `phoenixd` binary path.
    Idempotent: if the binary already exists for `version`, reuse it."""
    version = version or latest_version()
    dest = dest or install_dir()
    tag = _platform_tag()
    binary = dest / f"phoenixd-{version}-{tag}" / "phoenixd"
    if binary.exists():
        return binary

    url = f"{RELEASE_DL}/v{version}/phoenixd-{version}-{tag}.zip"
    dest.mkdir(parents=True, exist_ok=True)
    with httpx.Client(follow_redirects=True, timeout=120.0) as c:
        r = c.get(url)
        r.raise_for_status()
        with zipfile.ZipFile(io.BytesIO(r.content)) as z:
            z.extractall(dest)
    if not binary.exists():
        raise RuntimeError(f"phoenixd binary not found after unzip: {binary}")
    binary.chmod(binary.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return binary


# --- reading what first-run produced (pure; unit-tested with fixtures) ------
def read_http_password(conf_path: pathlib.Path = CONF_FILE) -> str:
    """Parse `http-password=...` out of phoenix.conf (the auto-generated API password, secret)."""
    if not conf_path.exists():
        raise FileNotFoundError(f"phoenix.conf not found at {conf_path} — has phoenixd run yet?")
    for line in conf_path.read_text().splitlines():
        m = re.match(r"\s*http-password\s*=\s*(.+?)\s*$", line)
        if m:
            return m.group(1).strip().strip('"').strip("'")
    raise RuntimeError("http-password not present in phoenix.conf")


def read_seed_words(seed_file: pathlib.Path = SEED_FILE) -> list[str]:
    """Read the BIP39 mnemonic phoenixd wrote to seed.dat. Returns the word list (12 or 24).
    Surfaced to the local wizard only — caller must not persist or transmit it."""
    if not seed_file.exists():
        raise FileNotFoundError(f"seed.dat not found at {seed_file} — has phoenixd run yet?")
    words = re.findall(r"[a-z]+", seed_file.read_text().lower())
    if len(words) not in (12, 24):
        raise RuntimeError(f"unexpected seed word count ({len(words)}) in {seed_file}")
    return words


def is_provisioned() -> bool:
    """True once phoenixd has generated its wallet (conf + seed present)."""
    return CONF_FILE.exists() and SEED_FILE.exists()


# --- first run --------------------------------------------------------------
def first_run(binary: pathlib.Path, timeout: float = 90.0) -> None:
    """Boot phoenixd once so it generates ~/.phoenix (seed + http-password), wait for those files,
    then stop this bootstrap process — the durable phoenixd.service takes over afterwards. No-op if
    already provisioned."""
    if is_provisioned():
        return
    proc = subprocess.Popen(
        [str(binary), "--agree-to-terms-of-service"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    try:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if is_provisioned():
                return
            if proc.poll() is not None:
                raise RuntimeError(f"phoenixd exited early (code {proc.returncode}) before generating a wallet")
            time.sleep(0.5)
        raise TimeoutError(f"phoenixd did not generate ~/.phoenix within {timeout}s")
    finally:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()


# --- systemd units (pure text; unit-tested) ---------------------------------
def phoenixd_service_unit(binary: pathlib.Path, user: str | None = None) -> str:
    from host.service_setup import current_user  # process owner, not $USER (sudo/su safe)
    user = user or current_user()
    return (
        "[Unit]\n"
        "Description=phoenixd (SAIL host Lightning node)\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "StartLimitIntervalSec=0\n\n"
        "[Service]\n"
        "Type=simple\n"
        f"User={user}\n"
        f"ExecStart={binary} --agree-to-terms-of-service\n"
        "Restart=always\n"
        "RestartSec=5\n\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def sail_host_dropin() -> str:
    """Drop-in so sail-host starts after, and is wanted-by, phoenixd when this tier is active."""
    return "[Unit]\nWants=phoenixd.service\nAfter=phoenixd.service\n"


def write_units(binary: pathlib.Path, deploy_dir: pathlib.Path | None = None) -> dict:
    """Write the unit + drop-in into the (gitignored) deploy/ dir and return the install commands.
    Installation needs root, so we surface the exact commands rather than assume sudo here."""
    deploy_dir = deploy_dir or pathlib.Path(__file__).resolve().parent.parent / "deploy"
    deploy_dir.mkdir(parents=True, exist_ok=True)
    unit = deploy_dir / "phoenixd.service"
    dropin = deploy_dir / "sail-host.service.d-phoenixd.conf"
    unit.write_text(phoenixd_service_unit(binary))
    dropin.write_text(sail_host_dropin())
    return {
        "unit": str(unit),
        "dropin": str(dropin),
        "install_commands": [
            f"sudo cp {unit} /etc/systemd/system/phoenixd.service",
            "sudo mkdir -p /etc/systemd/system/sail-host.service.d",
            f"sudo cp {dropin} /etc/systemd/system/sail-host.service.d/phoenixd.conf",
            "sudo systemctl daemon-reload",
            "sudo systemctl enable --now phoenixd",
        ],
    }


def try_install_units(binary: pathlib.Path, deploy_dir: pathlib.Path | None = None) -> dict:
    """Write the units, then attempt a passwordless install; fall back to surfacing the commands
    (same policy as the sail-host restart). Returns a JSON-able dict."""
    info = write_units(binary, deploy_dir)
    steps = [c.split()[1:] for c in info["install_commands"]]  # drop the leading 'sudo'
    try:
        for argv in steps:
            proc = subprocess.run(["sudo", "-n", *argv], capture_output=True, text=True, timeout=30)
            if proc.returncode != 0:
                info.update(installed=False, install_required=True,
                            error=(proc.stderr or proc.stdout).strip()[:200])
                return info
        info["installed"] = True
        return info
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        info.update(installed=False, install_required=True, error=str(e))
        return info


# --- orchestrator -----------------------------------------------------------
def provision(version: str | None = None) -> dict:
    """Full phoenixd setup. Returns the seed words (for the LOCAL wizard to display once) plus the
    service-install status. Writes PAYMENTS=phoenixd + PHOENIXD_API_PASSWORD into .env.host."""
    from host import config_writer  # local import to avoid a cycle

    binary = download_phoenixd(version)
    first_run(binary)
    password = read_http_password()
    seed_words = read_seed_words()  # surfaced locally only; never written elsewhere

    config_writer.update_env_file({
        "PAYMENTS": "phoenixd",
        "PHOENIXD_API_URL": os.getenv("PHOENIXD_API_URL", "http://127.0.0.1:9740"),
        "PHOENIXD_API_PASSWORD": password,
    })
    install = try_install_units(binary)
    return {"provisioned": True, "seed_words": seed_words, "service": install}
