"""
Host aliases — deterministic, unforgeable two-word names derived from a host's pubkey.

A host can't choose its alias (it falls out of its key), and there's no registrar: host and client
each compute the SAME name independently and offline. The client ALWAYS derives from the
signature-verified pubkey and ignores any alias a listing might carry, so a host can't stuff a
name in to impersonate another. Always render with the pubkey tail: "eloquent-cat · 2a2f".

Single source of truth: both host/ and client/ import derive_alias + the lists from HERE. Never
copy them — divergence would make the two sides derive different names and break verification.

THE WORDLISTS ARE A FROZEN CONTRACT. 1024 adjectives + 1024 nouns, generated once (see
tools/gen_aliaswords.py) and reviewed. Reordering or editing any entry silently renames every
existing host and breaks reputation continuity — treat this like a locked migration: don't touch it.
"""
from __future__ import annotations

import hashlib


def derive_alias(pubkey_hex: str) -> str:
    """Map a host pubkey to its two-word alias, e.g. "eloquent-cat".

    Pinned so host and client agree byte-for-byte: SHA-256 over the RAW 32 pubkey bytes (not the
    hex string), first 4 bytes big-endian -> two 10-bit indices (adjective from bits 10-19, noun
    from bits 0-9). Non-hex/odd identities (dev/mock keys) fall back to hashing the string bytes —
    both sides still agree because they run this same function.
    """
    try:
        raw = bytes.fromhex(pubkey_hex)
    except ValueError:
        raw = pubkey_hex.encode()
    n = int.from_bytes(hashlib.sha256(raw).digest()[:4], "big")
    return f"{ADJECTIVES[(n >> 10) & 0x3FF]}-{NOUNS[n & 0x3FF]}"


def alias_label(pubkey_hex: str) -> str:
    """The canonical display form: "<alias> · <first 4 hex of pubkey>". The tail disambiguates
    the ~1-in-1M word collisions; the pubkey remains the only thing that decides identity."""
    return f"{derive_alias(pubkey_hex)} · {pubkey_hex[:4]}"


ADJECTIVES = (
    "abnormal", "abrupt", "absorbed", "absurd", "abundant", "accepted", "accurate", "accursed",
    "actual", "adequate", "adopted", "adoptive", "adorable", "advanced", "adverse", "advised",
    "advisory", "affected", "afraid", "agile", "agreed", "ailing", "airborne", "airtight",
    "alive", "alleged", "allergic", "allied", "allowed", "alluring", "alpine", "amazing",
    "ambient", "amorous", "ample", "amusing", "angelic", "angrier", "angry", "animated",
    "anxious", "apparent", "applied", "archaic", "ardent", "arduous", "armed", "armored",
    "armoured", "arrogant", "arterial", "artistic", "ashamed", "assorted", "assumed", "assuming",
    "astral", "astute", "athletic", "atomic", "attached", "audible", "auld", "avid",
    "aware", "awesome", "awkward", "backdoor", "backed", "baffling", "banal", "bananas",
    "barbaric", "barbed", "bashful", "bats", "battled", "beaming", "bearable", "bearded",
    "beaten", "benign", "biased", "biblical", "bigger", "biggest", "biting", "bitty",
    "bizarre", "blatant", "blissful", "bloated", "blocked", "bloomed", "blurry", "bogus",
    "boiled", "bonded", "bonkers", "bony", "booted", "bossy", "bouncy", "brainy",
    "braver", "breathed", "breezy", "brushed", "bugs", "bulky", "bumpy", "burdened",
    "burned", "busier", "busiest", "candid", "canned", "capable", "carefree", "careful",
    "careless", "catchy", "cellular", "centered", "cervical", "chaotic", "charming", "chaste",
    "chatty", "checked", "cheeky", "cheerful", "cheery", "cheesy", "chewy", "childish",
    "chipper", "choosy", "chronic", "chubby", "chummy", "chunky", "civic", "civil",
    "classy", "clerical", "clever", "clingy", "clinical", "closed", "clouded", "cloudy",
    "clueless", "clumsy", "coarse", "coastal", "coated", "coherent", "colorful", "colossal",
    "coloured", "comfy", "comical", "communal", "composed", "confined", "conjugal", "corky",
    "corned", "cornered", "cosmic", "costly", "cowardly", "cracked", "crafty", "cramped",
    "cranial", "cranky", "crashing", "crass", "crazed", "crazier", "craziest", "creamy",
    "creative", "credible", "creepy", "crispy", "critical", "crooked", "crossed", "crowded",
    "crowned", "crowning", "crucial", "crunchy", "crusty", "cryptic", "cuddly", "culinary",
    "cultural", "cultured", "curious", "curly", "cushy", "cute", "cuter", "cutest",
    "cynical", "daft", "dashing", "dated", "decided", "decisive", "declared", "defiant",
    "definite", "deformed", "degraded", "dense", "deprived", "deserted", "deserved", "designed",
    "desired", "destined", "detached", "detailed", "devious", "devoid", "devoted", "devout",
    "diligent", "dinky", "dire", "directed", "discreet", "discrete", "disloyal", "dismal",
    "disposed", "distant", "distinct", "diverse", "divided", "doable", "dodgy", "dopey",
    "dormant", "dotted", "doubtful", "dramatic", "drastic", "drawn", "dreadful", "dreamy",
    "dreary", "drowsy", "drunken", "drying", "dubious", "durable", "earthly", "easier",
    "easiest", "eastern", "economic", "edgy", "educated", "eerie", "elderly", "elegant",
    "elevated", "eligible", "eloquent", "elusive", "eminent", "emptied", "empties", "enabling",
    "endless", "enduring", "engaged", "engaging", "enhanced", "enormous", "envious", "eternal",
    "ethereal", "ethical", "ethnic", "evasive", "everyday", "evident", "exalted", "excited",
    "exciting", "expanded", "explicit", "exposed", "extended", "extinct", "eyed", "fabulous",
    "faceless", "famished", "famous", "fancied", "faraway", "fated", "fateful", "fatter",
    "faulty", "favored", "fearful", "fearless", "fearsome", "feeble", "feisty", "femoral",
    "feral", "fertile", "festive", "fetching", "feudal", "feverish", "fickle", "fiddling",
    "fierce", "fiery", "figured", "filthy", "fingered", "finished", "finite", "fishy",
    "fitted", "fixed", "flabby", "flaky", "flashy", "flawed", "flawless", "fleeting",
    "flexible", "floating", "flooded", "floral", "flowery", "fluent", "fluffy", "focal",
    "foggy", "foolish", "forced", "forceful", "foreign", "forensic", "foxy", "fragile",
    "fragrant", "frantic", "freaky", "frigid", "frisky", "froggy", "frosty", "fruitful",
    "fruity", "funky", "funnier", "funniest", "furious", "furry", "fussy", "futile",
    "fuzzy", "gaga", "galactic", "gastric", "generic", "generous", "genetic", "genital",
    "genuine", "ghostly", "gifted", "gigantic", "girly", "glaring", "global", "gloomy",
    "glorious", "glum", "gnarly", "gooey", "goofy", "gorgeous", "gory", "graceful",
    "graphic", "grateful", "greasy", "greedy", "grievous", "grilled", "gritty", "groggy",
    "groovy", "grouchy", "grown", "gruesome", "grumpy", "guarded", "guilty", "gullible",
    "gutless", "gutsy", "hacking", "hairless", "hairy", "hallowed", "hammered", "handed",
    "handmade", "handsome", "happier", "happiest", "harassed", "hardened", "harmful", "harmless",
    "harsh", "haunted", "haunting", "hazy", "headed", "headless", "healthy", "hearted",
    "heated", "heavenly", "heavier", "heaviest", "hefty", "helpful", "helpless", "heroic",
    "hesitant", "hideous", "historic", "hoarse", "homely", "homemade", "homesick", "homey",
    "honest", "honorary", "hooded", "hooked", "hopeless", "hormonal", "horrible", "horrid",
    "horrific", "huge", "humane", "humbled", "humid", "humorous", "hungry", "hunted",
    "hurried", "hurtful", "iced", "icky", "iconic", "ignorant", "immature", "immense",
    "immersed", "imminent", "impacted", "implied", "impolite", "imposing", "impotent", "improper",
    "impudent", "impure", "inbound", "included", "indebted", "indoor", "inept", "infamous",
    "infinite", "inflated", "informal", "informed", "inherent", "inhuman", "inhumane", "injured",
    "innate", "insecure", "inserted", "insides", "insolent", "intact", "intense", "intrepid",
    "invasive", "inviting", "involved", "ironic", "itchy", "jagged", "jazzy", "jealous",
    "joyful", "joyous", "judicial", "juicy", "jumpy", "kinetic", "kooky", "labored",
    "landed", "larger", "largest", "lashed", "latent", "lawful", "lawless", "lazy",
    "leaky", "learned", "legal", "lengthy", "lenient", "liable", "lifelong", "likable",
    "likeable", "linear", "linked", "listed", "literary", "livid", "loaded", "lofty",
    "logical", "lone", "lonely", "longtime", "looser", "losing", "lousy", "lovable",
    "lovesick", "loving", "lowly", "loyal", "lucid", "luckier", "luckiest", "lukewarm",
    "lumbar", "luminous", "lumpy", "lunar", "luscious", "macabre", "magical", "magnetic",
    "mailed", "majestic", "mangy", "maniacal", "manned", "marital", "maritime", "marked",
    "martial", "masked", "massive", "maternal", "meager", "measly", "measured", "medieval",
    "mediocre", "mental", "merciful", "merrier", "messy", "metallic", "milky", "minded",
    "mindful", "mindless", "minimal", "missing", "mistaken", "mixed", "modest", "moist",
    "moldy", "monetary", "moonlit", "mounted", "mundane", "muscular", "mushy", "mutual",
    "mystical", "mythical", "nameless", "nasty", "nauseous", "nautical", "needless", "needy",
    "nervous", "neural", "nicer", "nicest", "nifty", "nimble", "nitro", "nitrous",
    "noir", "noisy", "nosy", "noted", "nuclear", "null", "numerous", "nutty",
    "obedient", "obsolete", "obvious", "oily", "olden", "oldest", "ominous", "ongoing",
    "optical", "optimal", "optional", "orthodox", "outdated", "outdoor", "overdue", "pained",
    "painful", "painless", "painted", "papal", "parental", "parted", "passed", "paternal",
    "peaceful", "peachy", "peaked", "pelvic", "penal", "perilous", "periodic", "perky",
    "pesky", "picked", "pickled", "picky", "pied", "piercing", "pious", "pitiful",
    "pivotal", "plastics", "playful", "poetic", "poignant", "pointed", "poised", "polar",
    "polished", "polite", "polluted", "pompous", "poor", "pops", "popular", "porky",
    "postal", "potent", "powered", "precise", "prepared", "prettier", "previous", "pricey",
    "prickly", "primal", "pristine", "prone", "prudent", "puffy", "punctual", "puny",
    "pure", "purest", "pushed", "pushy", "quaint", "queasy", "rabid", "ragged",
    "rainy", "rampant", "rancid", "rare", "rarest", "rational", "ratty", "reborn",
    "recent", "reckless", "reduced", "refined", "reformed", "regional", "related", "relevant",
    "reliable", "removed", "renal", "renowned", "repeated", "reserved", "resigned", "resolute",
    "resolved", "resting", "restless", "retiring", "rightful", "rigid", "rigorous", "ripe",
    "ripping", "risky", "robust", "rooted", "rotten", "rounded", "rude", "rugged",
    "runny", "rural", "sacred", "salted", "salty", "sane", "sanitary", "sassy",
    "scary", "scenic", "scrappy", "scratchy", "scrawny", "screwed", "screwy", "scruffy",
    "seasonal", "secluded", "seedy", "seismic", "selfish", "selfless", "sensory", "sensual",
    "serious", "severe", "shabby", "shadowy", "shady", "shaggy", "shaky", "shameful",
    "shifty", "shiny", "shocking", "shrewd", "sighted", "silky", "silvery", "similar",
    "sincere", "sinister", "sized", "sketchy", "skilled", "skillful", "skinned", "sleazy",
    "sleepy", "slender", "sliding", "slimy", "slippery", "sloppy", "sluggish", "smarty",
    "smashed", "smelly", "smoky", "smug", "snappy", "sneaking", "sneaky", "snoopy",
    "snowy", "soapy", "soggy", "solar", "solemn", "somber", "sonic", "sordid",
    "soulful", "soulless", "southern", "spacious", "sparing", "spatial", "speedy", "spicy",
    "spirited", "splendid", "spooky", "sporting", "sporty", "spotless", "spotted", "spotty",
    "squishy", "stacked", "stalked", "starred", "starry", "stated", "steamy", "stellar",
    "sterile", "stewed", "stony", "stopped", "strained", "strapped", "stricken", "strict",
    "striped", "stubborn", "studied", "stuffed", "stuffy", "stunning", "stylish", "suave",
    "subdued", "subtle", "suitable", "suited", "sultry", "superb", "supposed", "surgical",
    "surly", "sweaty", "swindled", "symbolic", "tacky", "tactical", "tall", "tamed",
    "tangled", "tanked", "tardy", "tasteful", "tasty", "tedious", "teeming", "teeny",
    "tempered", "temporal", "tempting", "tensed", "terrible", "terrific", "thankful", "thirsty",
    "thorough", "ticklish", "tidal", "tied", "timeless", "tiniest", "tipsy", "tireless",
    "tiresome", "tolerant", "touched", "touchy", "towering", "toxic", "tragic", "tranquil",
    "trashy", "tres", "tribal", "tricky", "trivial", "tropical", "trusting", "truthful",
    "trying", "tubby", "typical", "ulterior", "unable", "unarmed", "unbroken", "uncalled",
    "uncanny", "unclean", "unclear", "underage", "undone", "undue", "undying", "uneasy",
    "uneven", "unfair", "unhappy", "unharmed", "unheard", "united", "unjust", "unkind",
    "unlawful", "unlikely", "unlucky", "unmanned", "unmarked", "unpaid", "unreal", "unruly",
    "unsafe", "unsaid", "unsolved", "unspoken", "unstable", "unsure", "untold", "untrue",
    "unused", "unusual", "unwanted", "unwise", "unworthy", "uptight", "urgent", "usable",
    "used", "useless", "vacant", "vague", "valid", "valued", "varied", "vascular",
    "veiled", "versed", "vested", "viable", "vigilant", "vigorous", "vile", "viral",
    "virtual", "virtuous", "vivid", "volcanic", "wacky", "wary", "wasteful", "watchful",
    "watery", "wayward", "weak", "wealthy", "wedded", "wheeled", "whiny", "wider",
    "willed", "willful", "winged", "wired", "wiser", "wisest", "wishful", "wobbly",
    "woozy", "wordy", "worked", "worried", "wretched", "wrongful", "yawning", "youthful",
)

NOUNS = (
    "abdomen", "ability", "absence", "academy", "accident", "accused", "activity", "actor",
    "actress", "addition", "admiral", "adoption", "advice", "affair", "agency", "agenda",
    "agent", "aircraft", "airline", "airplane", "airport", "aisle", "album", "alliance",
    "allies", "amends", "amnesia", "analysis", "anatomy", "ankle", "antidote", "anxiety",
    "apology", "applause", "apples", "approval", "area", "arena", "argument", "army",
    "arrival", "arrow", "arson", "artery", "artist", "aspect", "aspirin", "assembly",
    "asset", "asylum", "athlete", "atom", "attorney", "audience", "audio", "aunt",
    "auntie", "aunty", "auto", "avatar", "avenue", "babe", "backing", "backup",
    "backyard", "baggage", "bakery", "balcony", "ballet", "banana", "bandit", "banker",
    "banking", "barrier", "baseball", "bases", "basis", "basket", "bathroom", "bathtub",
    "battery", "beast", "bedroom", "bedtime", "behalf", "behavior", "belief", "believer",
    "beta", "bidding", "biology", "birthday", "biscuit", "bladder", "blade", "blessing",
    "bloke", "boarding", "boiler", "bonus", "booking", "boots", "boredom", "bounty",
    "bouquet", "bout", "bowling", "boxer", "boxing", "bracelet", "brat", "bravery",
    "breakup", "breath", "briefing", "bulb", "bummer", "bureau", "buster", "buttons",
    "buzzer", "cadet", "calf", "caliber", "calling", "camera", "campus", "canteen",
    "canyon", "capacity", "cape", "caps", "capsule", "carbon", "cards", "cargo",
    "carnival", "carriage", "carrier", "carrot", "casino", "casting", "category", "cattle",
    "cavalry", "caviar", "ceiling", "cell", "cent", "century", "ceremony", "chaos",
    "chef", "chess", "chest", "children", "chili", "chimney", "chopper", "cinema",
    "circus", "citizen", "city", "clan", "clarity", "cleaner", "cleaning", "clearer",
    "clearing", "client", "climate", "clinic", "cloth", "clothing", "cobra", "cocoa",
    "cognac", "college", "cologne", "colonel", "colony", "column", "coma", "comedian",
    "comedy", "comes", "comet", "commerce", "computer", "comrade", "concept", "congress",
    "consul", "contempt", "context", "cooler", "corps", "corridor", "cosmos", "cottage",
    "council", "courage", "courier", "courtesy", "coverage", "covers", "cowboy", "coyote",
    "cracker", "creation", "creator", "creature", "creek", "crisis", "critic", "cupboard",
    "cupcake", "curfew", "currency", "curtains", "custody", "customer", "customs", "cutie",
    "daddy", "dairy", "dancer", "danger", "darkness", "data", "daughter", "daylight",
    "deadline", "dealer", "dealing", "debris", "debt", "decade", "decency", "decision",
    "defence", "defense", "delivery", "delta", "denial", "dentist", "depot", "depth",
    "descent", "desk", "dessert", "destiny", "detector", "device", "devotion", "dialing",
    "diary", "diesel", "dignity", "dilemma", "diner", "dinner", "dinosaur", "director",
    "disco", "disposal", "division", "doing", "donation", "donkey", "donor", "door",
    "doorbell", "doorman", "doorstep", "doorway", "dorm", "dough", "dowry", "drama",
    "drawer", "drawing", "dressing", "drilling", "driver", "driveway", "drummer", "duchess",
    "duct", "dude", "dungeon", "dunno", "duty", "dynasty", "earning", "economy",
    "edition", "editor", "effort", "election", "element", "elephant", "elevator", "embassy",
    "eminence", "emotion", "emperor", "empire", "employee", "employer", "empress", "ending",
    "energy", "engine", "entry", "envelope", "episode", "equation", "errand", "error",
    "essence", "estate", "eternity", "ethics", "evening", "event", "exam", "examiner",
    "exposure", "extent", "fabric", "facility", "facing", "fact", "factory", "faculty",
    "failure", "family", "feet", "festival", "fiance", "fiction", "fighter", "filling",
    "filming", "filth", "finale", "finch", "fireman", "firing", "fishing", "flea",
    "flyer", "font", "food", "footage", "football", "forehead", "foreman", "formula",
    "fossil", "fountain", "fraud", "freedom", "freeway", "freezer", "fridge", "fury",
    "fusion", "gadget", "galaxy", "gallery", "gambler", "gamma", "garbage", "garlic",
    "gasoline", "geek", "gender", "genius", "gents", "getaway", "girl", "glee",
    "goal", "goddess", "goodbye", "gorilla", "gospel", "governor", "granddad", "grandma",
    "grandpa", "grandson", "gravity", "gravy", "greed", "greeting", "grid", "grocery",
    "growth", "guidance", "guilt", "guitar", "guru", "hair", "haircut", "hallway",
    "handful", "handling", "hangover", "hardware", "headache", "heading", "hearts", "heaven",
    "height", "heir", "hello", "helmet", "helping", "heritage", "hero", "heroine",
    "hideout", "hiding", "highness", "highway", "history", "hobby", "hockey", "homeland",
    "homework", "honesty", "horizon", "horror", "hospital", "hostess", "hotel", "hour",
    "housing", "hubby", "humanity", "hunk", "hunting", "hydrogen", "idea", "idol",
    "ignition", "illusion", "immunity", "impulse", "income", "industry", "infantry", "info",
    "injury", "inmate", "inquiry", "insect", "insight", "intercom", "intimacy", "intruder",
    "invasion", "jackpot", "janitor", "jealousy", "jeep", "jeopardy", "jersey", "jewelry",
    "joker", "journal", "judgment", "juice", "jumper", "jungle", "justice", "karate",
    "karma", "keeper", "keeping", "ketchup", "kettle", "kiddo", "kidney", "kilo",
    "kindness", "kingdom", "ladies", "lake", "landlord", "language", "lantern", "laser",
    "laughter", "laundry", "lava", "lawn", "lawsuit", "lawyer", "leader", "learning",
    "leaves", "legacy", "legend", "lemonade", "length", "lens", "leopard", "letters",
    "lettuce", "liaison", "liar", "liberty", "library", "lice", "licking", "lied",
    "life", "lifetime", "lighting", "liking", "lining", "liver", "lives", "lizard",
    "lobster", "location", "locker", "logic", "lordship", "lottery", "lover", "loyalty",
    "luggage", "lung", "madam", "madame", "maestro", "magazine", "magician", "magnet",
    "maid", "mailbox", "mainland", "majesty", "majority", "makeup", "making", "mama",
    "mamma", "manager", "mankind", "manner", "manor", "mansion", "marathon", "mare",
    "marker", "marriage", "math", "matrix", "mattress", "meal", "meat", "media",
    "medic", "meeting", "member", "memo", "mentor", "menu", "mercury", "mermaid",
    "metaphor", "meteor", "method", "metro", "mice", "milady", "militia", "milord",
    "mining", "ministry", "miracle", "mischief", "missus", "mixture", "modeling", "mole",
    "moment", "money", "monsieur", "monster", "month", "monument", "mood", "moose",
    "morale", "morality", "mosquito", "motel", "motto", "movement", "movie", "mule",
    "mummy", "museum", "music", "musician", "mustache", "mustard", "mutt", "mystery",
    "myth", "napkin", "narrator", "nation", "nature", "navy", "necklace", "nephew",
    "news", "niece", "night", "noodle", "noon", "notebook", "notion", "nuisance",
    "nursery", "oath", "obstacle", "ocean", "octopus", "offence", "offender", "offense",
    "offering", "office", "omega", "onion", "opera", "operator", "opinion", "option",
    "organ", "origin", "ounce", "outcome", "outsider", "oven", "owner", "oxygen",
    "packing", "pact", "padre", "pageant", "painting", "palace", "paladin", "panda",
    "papa", "paradise", "paranoia", "parking", "parlor", "particle", "passion", "passport",
    "password", "pasta", "pastry", "path", "patriot", "patron", "paycheck", "payment",
    "payroll", "peanuts", "peasant", "penalty", "penguin", "pentagon", "period", "person",
    "petrol", "pharmacy", "phoenix", "photo", "physics", "pinky", "pint", "pitcher",
    "pizza", "planet", "plasma", "platform", "platoon", "plaza", "plea", "plumber",
    "plumbing", "poem", "poet", "poetry", "poker", "policy", "politics", "polo",
    "pony", "popcorn", "porch", "pork", "portal", "portrait", "postcard", "poster",
    "potato", "potion", "prayer", "precinct", "prep", "presence", "printer", "printing",
    "priority", "privacy", "problem", "producer", "product", "prom", "property", "proposal",
    "protein", "protocol", "province", "pudding", "pumping", "pumpkin", "pupil", "puppet",
    "puppy", "pursuit", "quantum", "quid", "radar", "radius", "railway", "rainbow",
    "reaction", "reactor", "reader", "reading", "reality", "realm", "receiver", "recipe",
    "recorder", "recovery", "regime", "region", "reindeer", "relation", "relief", "religion",
    "reporter", "republic", "residue", "response", "reunion", "revenue", "revolver", "rhythm",
    "ripper", "robot", "rodeo", "role", "roller", "rookie", "roommate", "rooster",
    "rover", "royalty", "rubbing", "ruler", "runner", "runway", "safety", "sailor",
    "sake", "salad", "salesman", "salon", "saloon", "samurai", "sausage", "saying",
    "says", "scanner", "scenario", "scene", "scenery", "scholar", "science", "scooter",
    "scope", "scorpion", "secrecy", "sector", "security", "seller", "semester", "seminar",
    "senate", "senator", "sensor", "series", "sermon", "serpent", "serum", "servant",
    "services", "serving", "session", "setup", "sewing", "shaving", "sheep", "shelf",
    "sheriff", "shipment", "shipping", "shooter", "shopping", "showing", "shredder", "sidewalk",
    "sinking", "siren", "skeleton", "skiing", "skull", "sniffles", "soccer", "society",
    "soda", "sofa", "software", "solitude", "solution", "soul", "source", "speaker",
    "species", "specimen", "speech", "spelling", "spider", "spine", "sports", "squad",
    "squadron", "squirrel", "stadium", "statue", "status", "steak", "steed", "stench",
    "stops", "storage", "strategy", "street", "strength", "stripper", "student", "studio",
    "stuffing", "subway", "success", "suction", "suitcase", "suite", "sultan", "summit",
    "sunlight", "surfing", "surgeon", "surgery", "survival", "survivor", "sushi", "sweater",
    "sweetie", "sword", "sympathy", "symphony", "system", "tablet", "taco", "tale",
    "talent", "tales", "tang", "taps", "tavern", "teacher", "teaching", "teal",
    "tech", "teenager", "telegram", "teller", "telly", "tennis", "tension", "text",
    "theater", "theatre", "theme", "theory", "therapy", "thesis", "thief", "thing",
    "throat", "ticking", "tiger", "timer", "timing", "toad", "toilet", "tomato",
    "tongues", "topic", "tornado", "tractor", "trailer", "training", "traveler", "treasury",
    "treaty", "triangle", "tribe", "tribute", "trophy", "truce", "trunk", "truth",
    "tuition", "tummy", "tuna", "turkey", "uncle", "unit", "universe", "upside",
    "user", "vaccine", "valve", "vampire", "vanilla", "vanity", "variety", "vase",
    "vehicle", "venom", "venue", "verdict", "version", "vessel", "vicinity", "video",
    "villa", "village", "villain", "violence", "violin", "virtue", "virus", "visitor",
    "volcano", "volume", "voyager", "waist", "waitress", "wallet", "wand", "wardrobe",
    "warmer", "warmth", "warrior", "washing", "weakness", "wealth", "weasel", "wedding",
    "werewolf", "wheat", "whitey", "wife", "wildlife", "winner", "wisdom", "wives",
    "wolves", "women", "wool", "worker", "workout", "workshop", "wormhole", "worms",
    "wrist", "writer", "writing", "year", "yoga", "yogurt", "youth", "zombie",
)
